server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mysql_db?useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true&useUnicode=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user
    password: 1234

  data:
    mongodb:
      uri: mongodb://localhost:27017/mongo_db?authSource=admin

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

logging:
  level:
    org.hibernate.SQL: debug
