spring:
  datasource:
    url: jdbc:mysql://docker_server_mysql_db:3306/mysql_db?serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  data:
    mongodb:
      uri: mongodb://admin:1234@docker_server_mongo_db:27017/mongo_db?authSource=admin&authMechanism=SCRAM-SHA-1
  rabbitmq:
    host: docker_server_rabbitmq
    port: 5672
    username: admin
    password: 1234
  redis:
    host: docker_server_redis
    port: 6379
  cache:
    type: redis
sample-rabbitmq:
  queue: sample.queue
  exchange: sample.exchange
  routing-key: sample.key
