server:
  port: 80
  name: "Docker Practice"

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    open-in-view: true

logging:
  level:
    org.hibernate.SQL: debug

management:
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  version: 0.1
  swagger-ui:
    path: /docs
    defaultModelsExpandDepth: 3
    default-model-expand-depth: 3
