server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mysql_db?useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true&useUnicode=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user
    password: 1234

  data:
    mongodb:
      uri: mongodb://localhost:27017/mongo_db?authSource=admin

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

  redis:
    host: localhost
    port: 6379
  cache:
    type: redis

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

logging:
  level:
    org.hibernate.SQL: debug

sample-rabbitmq:
  queue: sample.queue
  exchange: sample.exchange
  routing-key: sample.key
