server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/mysql_db?serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  data:
    mongodb:
      uri: mongodb://mongo:27017/mongo?authSource=admin

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: 1234

  redis:
    host: redis
    port: 6379
  cache:
    type: redis

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    open-in-view: true

logging:
  level:
    org.hibernate.SQL: debug

sample-rabbitmq:
  queue: sample.queue
  exchange: sample.exchange
  routing-key: sample.key
